# TENSORFLOW: Alô Mundo!

Esta aula cobre fundamentos, grafos de tensores, tensores, variáveis, placeholders e _operações_ $\mathcal{M}_3$.



<a id="ref2"></a>
# Como o TensorFlow funciona?

Para executar código em diferentes hardwares desde CPUs a GPUS, o TensorFlow define _computações como grafos_. Estas computações são chamadas operações (_ops_). De forma geral, programar em TensorFlow é definir uma série de ops, criando um grafo geral de computação e, então, executar este grafo em uma sessão.

Executar o grafo em um sessão pode ser visto como compilá-lo para o hardware alvo e, então, executá-lo. 

Por exemplo, abaixo temos a representação de um grafo em TensorFlow. _W_, _x_ e _b_ são tensores representados como arestas no grafo. _MatMul_ é uma operação sobre _W_ e _x_, cujo resultado será parâmetro para _Add_ para que seja somada com _b_. Os vetores resultantes vão sendo propagados até que o vetor _C_ receba a avaliação final do grafo.

<img src='images/mod_ID_23_final.png'>


### Importando TensorFlow

In [1]:
import tensorflow as tf

E:\Anaconda\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


<a id="ref3"></a>
# Criando um Grafo

Vamos criar a operação c = a + b.

Entre as operações suportadas, é possível usar __source operations__, que não precisam de informação de entrada. Em geral, elas existem para fornecer entradas para outras operações.

Vamos criar source ops para definir duas constantes -- tensores [2] e [3]:

In [2]:
a = tf.constant([2])
b = tf.constant([3])

Para somá-las, podemos usar __tf.add()__ ou simplesmente +. 

In [3]:
c = tf.add(a,b)
#c = a + b        # equivalente

Note que c não tem o valor de a+b. Para a atribuição ser executada, é necessário criar uma sessão.

In [4]:
session = tf.Session()

Agora podemos executar a computação c:

In [5]:
result = session.run(c)
print(result)

[5]


Ao fim do uso da sessão, devemos fechá-la:

In [6]:
session.close()

Para evitar ter que sempre lembrar de fechar sessões, vamos usar o comando de guarda __with__ do Python, que garante a abertura e fechamento da Sessão:

In [7]:
with tf.Session() as session:
    result = session.run(c)
    print(result)

[5]


Alternativamente, __apenas__ no ambiente jupyter, podemos usar sessões interativas, que são válidas para todo notebook até serem fechadas:

In [2]:
session = tf.InteractiveSession()

session.close()

Muito complexo? Bom, isso é programar em TensorFlow:

1. defina o grafo da computação
2. execute-o em uma sessão

### O que é um Tensor?

<div class="alert alert-success alertsuccess" style="margin-top: 20px">
<font size = 3><strong>Para TensorFlow, é um tipo usado para representar dados em um grafo de computação. Como os valores fluem pelo grafo como tensores, temos TensorFlow</strong></font>
<br>
<br>
O termo __tensor__ vem do Latin e significa algo como "algo que estica/comprime". É um objeto matemático criado inicialmente para o estudo da expansão/compressão de materias sobre tensão. Representa uma generalização do conceito de matrizes multi-dimensionais, sem a restrição de associação com linearidade. 

<p></p>

</div>

Para entender o conceito de multi-dimensionalidade, é necessário entender o conceito Físico de dimensões:<br>
<img src="images/Dimension_levels.svg"/>
<div style="text-align:center">[[Image Source]](https://en.wikipedia.org/wiki/Dimension) </div>

Dimensão zero se refere ao ponto (escalar), a um objeto isolado ou a um item único.

Dimensão 1 é linha (vetor). A dimensão 1 contém infinitas dimensões 0 (ou uma amostra delas, em um vetor ;)).

Dimensão 2 é a superfície (vetor 2D ou matriz). Uma série infinita de linhas ao longo de uma linha infinita. 

Dimensão 3 é o volume ou matriz 3D. Uma série infinita de superfícies ao longo de uma linha infinita.

Dimensão 4 é o hiperespaço (ou o espaço-tempo). Um volume variando ao longo do tempo ou uma série infinita de volumes ao longo de uma linha infinita. E assim em diante...

Sumarizando:<br><br>
<table style="width:100%">
  <tr>
    <td><b>Dimensão</b></td>
    <td><b>Representação</b></td> 
    <td><b>Matemática</b></td>
    <td><b>Programação</b></td>
  </tr>
  
  <tr>
    <td>Zero </td>
    <td>Ponto</td> 
    <td>Escalar</td>
    <td>[ 1 ]</td>
  </tr>

  <tr>
    <td>Um</td>
    <td>Linha</td> 
    <td>Vetor (Séries of Números) </td>
    <td>[ 1,2,3,4,... ]</td>
  </tr>
  
   <tr>
    <td>Dois</td>
    <td>Surpefícies</td> 
    <td>Matriz (Série de Vetores)</td>
    <td>[ [1,2,3,4,...], [1,2,3,4,...], [1,2,3,4,...],... ]</td>
  </tr>
  
   <tr>
    <td>Três</td>
    <td>Volume</td> 
    <td>Tensor (Série de Matrizes)</td>
    <td>[ [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...] ,...]... ]</td>
  </tr>
  
</table>

<a id="ref5"></a>
# Por que usar tensores?

Tensores permitem que conjuntos de números sejam arranjados (shape) do modo mais adequado (inclusive para o hardware).

É particularmente útil com imagens devido à forma como a informação é codificada em imagens. 

Como imagens tem altura e largura (2 dimensões), é fácil pensá-las como matrizes de números. Como elas tem cores (terceira dimensão), é mais fácil ainda pensá-las como um tensor de números (um cubo), ou seja um vetor de matrizes de números.

A codificação mais comum de cores é a RGB (Red, Blue e Green), em que a cor é reprensentada por 3 cores primárias. A imagem pode ser pensada então como tendo três canais, um para cada cor:

<img src='images/IC676790.png'>
<div style="text-align:center">[[Image Source]](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424131.aspx)</div>

<a id="ref4"></a>
# Definindo tensores
Agora vamos definir esses objetos em TensorFlow:

In [8]:
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]], 
                       [[4,5,6],[5,6,7],[6,7,8]] , 
                       [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session() as session:
    result = session.run(Scalar)
    print("Escalar (1):\n %s \n" % result)
    result = session.run(Vector)
    print("Vetor (3 entradas) :\n %s \n" % result)
    result = session.run(Matrix)
    print("Matriz (3x3 entradas):\n %s \n" % result)
    result = session.run(Tensor)
    print("Tensor (3x3x3 entradas) :\n %s \n" % result)

Escalar (1):
 [2] 

Vetor (3 entradas) :
 [5 6 2] 

Matriz (3x3 entradas):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entradas) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



Vamos praticar com o uso destas estruturas:

In [9]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

first_operation = tf.add(Matrix_one, Matrix_two)
second_operation = Matrix_one + Matrix_two

with tf.Session() as session:
    result = session.run(first_operation)
    print("Usando TensorFlow tf.add:")
    print(result)
    result = session.run(second_operation)
    print("Usando +:")
    print(result)

Usando TensorFlow tf.add:
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Usando +:
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [10]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

second_operation = Matrix_one * Matrix_two

with tf.Session() as session:
    result = session.run(second_operation)
    print(result)

[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]


Note que * corresponde à multiplicação elemento-a-elemento ou produto de Hadamard. <br>

Para multiplicação de matrizes, usamos __tf.matmul()__:

In [11]:
Matrix_one = tf.constant([[2,3],[3,4],[5,6]])
Matrix_two = tf.constant([[2,3,4],[3,4,5]])

first_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session() as session:
    result = session.run(first_operation)
    print("tf.matmul :")
    print(result)

tf.matmul :
[[13 18 23]
 [18 25 32]
 [28 39 50]]


Note que, embora seja trivial definir estas funções, é sempre melhor optar pelas implementações dadas pela biblioteca, se estiverem disponíveis. Em geral, elas foram implementadas de forma a tirar maior proveito de paralelização no hardware.

**Exercício**: Dadas as matrizes $m_1$ e $m_2$, calcule $m_3 = m_1 \times m_2^T$:

$$
m1 = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$$

$$
m2 = \begin{bmatrix}
7 & 8 & 9 \\
10 & 11 & 12 \\
\end{bmatrix}
$$

<div align="right">
<a href="#mult1" class="btn btn-default" data-toggle="collapse">Solução #1</a>
</div>
<div id="mult1" class="collapse">
```
import tensorflow as tf

# construcao

m1 = tf.constant([[1,2,3], [4,5,6]])
m2 = tf.constant([[7,8,9], [10,11,12]])

m3 = tf.matmul(m1, tf.transpose(m2))

# execução

s = tf.Session()
res = s.run(m3)
print res
s.close()
```
</div>

<a id="ref6"></a>
# Variáveis

Para definir variáveis, usamos o comando __tf.variable()__. Variáveis precisam ser iniciadas antes que o grafo seja avaliado. Isto é feito com __tf.global_variables_initializer()__.

In [12]:
state = tf.Variable(0)
state

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

Vamos criar um contador:

In [13]:
one = tf.constant(1)
#new_value = tf.add(state, one)
update = tf.assign(state, state + one)

Também devemos definir a operação de inicialização:

In [14]:
init_op = tf.global_variables_initializer()

Uma vez iniciada a sessão, devemos executar o grafo e iniciar suas variáveis. Para observar as mudanças na variável __state__, vamos imprimi-la logo após a inicialização e, então, atualizar seu valor algumas vezes em um laço:

In [15]:
with tf.Session() as session:
  session.run(init_op)
  print(session.run(state), '<- depois de iniciada e antes do loop')
  for _ in range(3):
    session.run(update)
    print(session.run(state))

0 <- depois de iniciada e antes do loop
1
2
3


**Exercício**: dado o código abaixo, escreva um equivalente em tensorflow:

```python
cont = 1  # iniciar
while cont<1024:
    print cont # uso 
    cont = cont * 2 # atualizacoes
```

<div align="right">
<a href="#cont" class="btn btn-default" data-toggle="collapse">Solução #1</a>
</div>
<div id="cont" class="collapse">
```
import tensorflow as tf

# construcao
contador = tf.Variable(1, dtype = tf.int32, name = 'contador')
incremente = tf.assign(contador, contador *2)
# contador = contador *2

init = tf.global_variables_initializer()

# execução

with tf.Session() as s:
    s.run(init)
    res = contador.eval()
    while res < 1024:
        print(res)
        res = s.run(incremente)
```
</div>

<a id="ref7"></a>
# Placeholders

Agora vamos ver como alimentar um grafo com dados que vem de fora do modelo que estamos criando. Para isso, vamos usar _placeholders_.

Placeholders são as portas de entrada do seu modelo. São definidos com <br/> <b>tf.placeholder(_tipo_)</b>, onde <b>_tipo_</b> especifica o tipo de dados (integers, floating points, strings, booleans) junto com sua precisão (8, 16, 32, 64) em bits:

|Data type	|Python type|Description|
| --------- | --------- | --------- |
|DT_FLOAT	|tf.float32	|32 bits floating point.|
|DT_DOUBLE	|tf.float64	|64 bits floating point.|
|DT_INT8	|tf.int8	|8 bits signed integer.|
|DT_INT16	|tf.int16	|16 bits signed integer.|
|DT_INT32	|tf.int32	|32 bits signed integer.|
|DT_INT64	|tf.int64	|64 bits signed integer.|
|DT_UINT8	|tf.uint8	|8 bits unsigned integer.|
|DT_STRING	|tf.string	|Variable length byte arrays. Each element of a Tensor is a byte array.|
|DT_BOOL	|tf.bool	|Boolean.|
|DT_COMPLEX64	|tf.complex64	|Complex number made of two 32 bits floating points: real and imaginary parts.|
|DT_COMPLEX128	|tf.complex128	|Complex number made of two 64 bits floating points: real and imaginary parts.|
|DT_QINT8	|tf.qint8	|8 bits signed integer used in quantized Ops.|
|DT_QINT32	|tf.qint32	|32 bits signed integer used in quantized Ops.|
|DT_QUINT8	|tf.quint8	|8 bits unsigned integer used in quantized Ops.|

<div style="text-align:center">[[Table Source]](https://www.tensorflow.org/versions/r0.9/resources/dims_types.html)</div>


Vamos criar um placeholder para um número real de 32 bits:

In [16]:
a = tf.placeholder(tf.float32)

E definir uma multiplicação com ele:

In [17]:
b = a*2

Para usar o placeholder, é necessário definir o valor do argumento feed_dict de run(). Este argumento define um dicionário que indica o nome e o valor que o palceholder vai ter:

In [18]:
with tf.Session() as sess:
    result = sess.run(b, feed_dict={a:3.5})
    print('2*a =', result)

2*a = 7.0


Qualquer tipo de tensor pode ser passado para um placeholder:

In [19]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , 
                [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b, feed_dict = dictionary)
    print('2*a =', result)

2*a = [[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


No exemplo a seguir, usamos placeholders para definir os valores de uma equação de segundo grau:

In [20]:
tf.reset_default_graph()

In [23]:
a = tf.placeholder(tf.complex64, name='a')
b = tf.placeholder(tf.complex64, name='b')
c = tf.placeholder(tf.complex64, name='c')

#with tf.name_scope('delta'):
delta = b*b - 4*a*c
with tf.name_scope('x0'):
    x0 = (-b - tf.sqrt(delta))/(2*a)
with tf.name_scope('x1'):
    x1 = (-b + tf.sqrt(delta))/(2*a)

In [24]:
with tf.Session() as s:
    rx0, rx1 = s.run([x0, x1], feed_dict={a:1., b:4., c:5.})
    print (rx0, rx1)
    tf.summary.FileWriter('logs/tfhelloworld', s.graph).close()

(-2-1j) (-2+1j)


Dê uma olhada agora no tensorboard para ver o grafo gerado.

<a id="ref8"></a>
# Operações

TensorFlow define uma grande variedade de operações que podem ser realizadas com tensores, tais como _tf.matmul_, _tf.add_ e _tf.nn.sigmoid_.  
<div class="alert alert-success alertsuccess" style="margin-top: 20px">Para uma lista de operações, olhe a API python: https://www.tensorflow.org/versions/r1.1/api_docs/python/index.html</div>

In [25]:
a = tf.constant([5])
b = tf.constant([2])
c = a + b
d = a - b

with tf.Session() as session:
    result = session.run(c)
    print('c =: %s' % result)
    result = session.run(d)
    print('d =: %s' % result)

c =: [7]
d =: [3]


Note que a fase de construção do grafo pode envolver operações complexas. Por exemplo, imagine que queremos definir uma sequência fatorial, ou seja, uma sequência $S$ de números que começa com 1 e cujo valor do $i$-ésimo número é $i S_{i-1}$. Por exemplo, os 5 primeiros valores de $S$ são [1, 1, 2, 6, 24].

Podemos definir essa sequencia em TF assim:

In [26]:
tf.reset_default_graph()

In [27]:
S = [tf.constant(1)]
i = 1
while i < 5:
    S = S + [i * S[i-1]]
    i = i + 1

In [28]:
with tf.Session() as s:
    res = s.run(S)
    print(res)
    tf.summary.FileWriter('logs/tfhelloworld', s.graph)

[1, 1, 2, 6, 24]


In [29]:
tf.reset_default_graph()

In [30]:
S = [tf.constant(1, name="S0")]
i = 1
while i < 5:
    S = S + [tf.multiply(i, S[i-1], name = "ixS" + str(i-1))]
    i = i + 1

In [31]:
with tf.Session() as s:
    res = s.run(S)
    print(res)
    tf.summary.FileWriter('logs/tfhelloworld', s.graph).close()

[1, 1, 2, 6, 24]


**Exercício**: Faça um grafo em tensorflow que gere uma lista com os dez primeiros membros da sequência de Fibonnaci:

$$
F_0 = 1 \\
F_1 = 1 \\
F_n = F_{n-1} + F_{n-2},\forall n>=2 
$$


<div align="left">
<a href="#fib" class="btn btn-default" data-toggle="collapse">Dica</a>
</div>
<div id="fib" class="collapse">
Em python puro, o codigo seria:
```python
fib = [1,1]
i = 2
while i < 6:
    fib = fib + [fib[i-1] + fib[i-2]]
    i += 1
print fib
```
</div>

<div align="right">
<a href="#fib" class="btn btn-default" data-toggle="collapse">Solução #1</a>
</div>
<div id="fib" class="collapse">
```
tf.reset_default_graph()

fib = [tf.constant(1,name='fib0'),tf.constant(1,name='fib1')]

i = 2
while i<6:
    fib = fib+ [tf.add(fib[i-1],fib[i-2],name='fib'+str(i))]
    i+=1

with tf.Session() as s:
    print(s.run(fib))
    tf.summary.FileWriter('logs/fib', s.graph).close()
```
</div>

### Referências:

https://www.tensorflow.org/versions/r0.9/get_started/index.html<br />
http://jrmeyer.github.io/tutorial/2016/02/01/TensorFlow-Tutorial.html<br />
https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html<br />
https://www.tensorflow.org/versions/r0.9/resources/dims_types.html<br />
https://en.wikipedia.org/wiki/Dimension<br />
https://book.mql4.com/variables/arrays<br />
https://msdn.microsoft.com/en-us/library/windows/desktop/dn424131(v=vs.85).aspx<br />

Este curso é baseado em material da [Big Data University](https://bigdatauniversity.com/?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). Assim, segue os termos da [licença do MIT](https://bigdatauniversity.com/mit-license/). Aula modificada por Marco Cristo e André Carvalho a partir de versão de _Rafael Belo da Silva_